package com.ahmadabuhasan.pointofsales

/*
 * Created by Ahmad Abu Hasan (C) 2022
 */

object Constant {

    const val ADMIN = "admin"
    const val CANCEL = "Cancel"
    const val CART_ID = "cart_id"
    const val CATEGORY_ID = "category_id"
    const val CATEGORY_NAME = "category_name"
    const val COMPLETED = "Completed"
    const val CUSTOMER_ADDRESS = "customer_address"
    const val CUSTOMER_CELL = "customer_cell"
    const val CUSTOMER_EMAIL = "customer_email"
    const val CUSTOMER_ID = "customer_id"
    const val CUSTOMER_NAME = "customer_name"
    const val DAILY = "daily"
    const val DISCOUNT = "discount"
    const val EXPENSE_AMOUNT = "expense_amount"
    const val EXPENSE_DATE = "expense_date"
    const val EXPENSE_ID = "expense_id"
    const val EXPENSE_NAME = "expense_name"
    const val EXPENSE_NOTE = "expense_note"
    const val EXPENSE_TIME = "expense_time"
    const val ID = "id"
    const val INVOICE_ID = "invoice_id"
    const val MANAGER = "manager"
    const val MONTHLY = "monthly"
    const val ORDER_DATE = "order_date"
    const val ORDER_DETAILS_ID = "order_details_id"
    const val ORDER_ID = "order_id"
    const val ORDER_PAYMENT_METHOD = "order_payment_method"
    const val ORDER_RECEIPT = "order_receipt"
    const val ORDER_STATUS = "order_status"
    const val ORDER_TIME = "order_time"
    const val ORDER_TYPE = "order_type"
    const val ORDER_TYPE_NAME = "order_type_name"
    const val ORDER_TYPE_ID = "order_type_id"
    const val PAYMENT_METHOD_ID = "payment_method_id"
    const val PAYMENT_METHOD_NAME = "payment_method_name"
    const val PENDING = "Pending"
    const val PRICE = "price"
    const val PROCESSING = "Processing"
    const val PRODUCT_BUY_PRICE = "product_buy_price"
    const val PRODUCT_CATEGORY = "product_category"
    const val PRODUCT_CODE = "product_code"
    const val PRODUCT_DESCRIPTION = "product_description"
    const val PRODUCT_ID = "product_id"
    const val PRODUCT_IMAGE = "product_image"
    const val PRODUCT_NAME = "product_name"
    const val PRODUCT_ORDER_DATE = "product_order_date"
    const val PRODUCT_PRICE = "product_price"
    const val PRODUCT_QTY = "product_qty"
    const val PRODUCT_SELL_PRICE = "product_sell_price"
    const val PRODUCT_STOCK = "product_stock"
    const val PRODUCT_SUPPLIER = "product_supplier"
    const val PRODUCT_WEIGHT = "product_weight"
    const val PRODUCT_WEIGHT_UNIT = "product_weight_unit"
    const val PRODUCT_WEIGHT_UNIT_ID = "product_weight_unit_id"
    const val SHARED_PREF_NAME = "com.app.restaurantpos"
    const val SHOP = "shop"
    const val SHOP_ADDRESS = "shop_address"
    const val SHOP_CONTACT = "shop_contact"
    const val SHOP_CURRENCY = "shop_currency"
    const val SHOP_EMAIL = "shop_email"
    const val SHOP_ID = "shop_id"
    const val SHOP_NAME = "shop_name"
    const val SP_PASSWORD = "password"
    const val SP_PHONE = "phone"
    const val SP_USER_NAME = "user_name"
    const val SP_USER_TYPE = "user_type"
    const val STOCK = "stock"
    const val SUPPLIERS_ADDRESS = "suppliers_address"
    const val SUPPLIERS_CELL = "suppliers_cell"
    const val SUPPLIERS_CONTACT_PERSON = "suppliers_contact_person"
    const val SUPPLIERS_EMAIL = "suppliers_email"
    const val SUPPLIERS_ID = "suppliers_id"
    const val SUPPLIERS_NAME = "suppliers_name"
    const val TABLE_NO = "table_no"
    const val TAX = "tax"
    const val USER_NAME = "user_name"
    const val USER_PASSWORD = "user_password"
    const val USER_PHONE = "user_phone"
    const val USER_TYPE = "user_type"
    const val WEIGHT_ID = "weight_id"
    const val WEIGHT_UNIT = "weight_unit"
    const val YEARLY = "yearly"

    @JvmField var customers = "customers"
    @JvmField var expense = "expense"
    @JvmField var orderDetails = "order_details"
    @JvmField var orderList = "order_list"
    @JvmField var paymentMethod = "payment_method"
    @JvmField var productCart = "product_cart"
    @JvmField var productCategory = PRODUCT_CATEGORY
    @JvmField var products = "products"
    @JvmField var suppliers = "suppliers"
    @JvmField var users = "users"
}
